db_file: "bot.db"
bot_url: "https://t.me/todo_reminder_bot"
messages:
  responses:
    start: "Привет! Чтобы получать уведомления из Todoist, для начала тебе нужно дать мне на это доступ. Для этого переходи по ссылке:\n%s"
    already_authorized: "Ты уже авторизирован. Бот будет присылать уведомления по твоим задачам"
    no_message: "В данный момент я не принимаю сообщений, я могу только отсылать уведомления о задачах"
    unknown_command: "Неподдерживаемая команда"

  errors:
    default: "Произошла неизвестная ошибка"
    unauthorized: "Ты не авторизирован. Используй команду /start"
    unable_to_save: "Увы, не удалось сохранить ссылку. Попробуй еще раз позже."
